name: Pull Request Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: frontEnd/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/frontEnd/package.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
        working-directory: frontEnd

      - name: Run Tests
        run: npm test
        working-directory: frontEnd
